### ISSUE TITLE
Error 404 after successful setup

### ISSUE THREAD

**Issue by nickroffeis** [neopostmodern/wohnungsbot#100]
After successfully setting everything up, Bot is unable to load pages on ImmoScout24 as it always shows a non-existing or error page.
<img width="1312" alt="Bildschirmfoto 2022-04-28 um 14 38 16" src="https://user-images.githubusercontent.com/81181743/165753652-99ee16eb-e227-4ebb-beb4-8d6b15bcd251.png">

**Comment by neopostmodern** [comment]
Can you please check if #91 covers your issue?

**Comment by nickroffeis** [comment]
Awesome, works! Cheers
