### ISSUE TITLE
Bot getting stuck because of cookies popup

### ISSUE THREAD

**Issue by ladolcevitaa** [neopostmodern/wohnungsbot#101]
First of all thanks a lot for this amazing tool!

To the issue: Not sure if there is something that I'm missing or if there is an easy fix, but the bot keeps getting stuck on a cookie popup from Immoscout before the login. 

Haven't been getting these so far but now it's always there and the bot gets stuck. 

Any ideas? 

Thanks

**Comment by almysun** [comment]
I have the same problem!

**Comment by almysun** [comment]
I have the same issue (mac)

**Comment by baragodu** [comment]
hey, the same problem here ! i really count with this help to get a flat here.

Well done !!

**Comment by neopostmodern** [comment]
The bug seems to affect all usage, not just the login. Seems like the cookie popup implementation has changed.

**Comment by ladolcevitaa** [comment]
Sorry I'm not really familiar with Github, does that mean the issue is fixed now? Thanks

**Comment by neopostmodern** [comment]
Yes, the fix has been released in [1.5.0](https://github.com/neopostmodern/wohnungsbot/releases/tag/v1.5.0).

**Comment by ladolcevitaa** [comment]
You are a legend!! Honestly thank you so much for this work and I can't believe how quickly the bug was fixed.
