### ISSUE TITLE
cant install on Ubuntu 20.043 LTS 64-bits

### ISSUE THREAD

**Issue by Babyelefant1312** [neopostmodern/wohnungsbot#104]
Heyho,
i tried to install it via doubleclick but it says,i have not the right program for it.
tried to look it up on the net which would be the right one. seems to be fuse for AppImages right?
Well then i checked, its up to date an installed.
Any help here for me? I would appreciate it.
Thanks

**Comment by neopostmodern** [comment]
Does the second-last point of the [FAQ](https://wohnungsbot.de/faq.html) address your problem? It's only in German right now, but basically it's about whether you allowed to execute the AppImage itself – it's not opened in another program. So:
- either `chmod +x Wohnungsbot-1.5.0.AppImage`
- or in the file manager: right-click > `Properties` > `Permissions` > `Allow executing file as program`
...then you should be able to double-click or execute from the CLI.

Feel free to re-open if that doesn't solve your issue.

**Comment by Babyelefant1312** [comment]
yeah, thank you this is awesome. sorry for being so noobie having forgotten to check on de faq's..
thanks and bye
