### ISSUE TITLE
Building for Linux not working on Windows

### ISSUE THREAD

**Issue by drblaui** [neopostmodern/wohnungsbot#105]
Using the `npm run package-linux` Commands fails, since the builder request the `https://service.electron.build` url, which is down and [seems to have been for quite a while](https://github.com/electron-userland/electron-build-service/issues/17). I don't know if the Server behind the domain is just offline sometimes or if it will be down always. Anyway the build can't be done reliably 

As much as I can gather, this should only be a problem on Windows Environments

**Comment by neopostmodern** [comment]
I have no Windows computer and no idea how to solve this. What would this be necessary for?

The best way I can think of to achieve this (with no access to a Linux machine to build on) would be setting up a GitHub Actions workflow in a fork and then build natively on Linux, see https://github.com/neopostmodern/wohnungsbot/blob/master/.github/workflows/build-electron-dev.yml#L11 (it builds natively on three separate operating systems).

**Comment by drblaui** [comment]
> What would this be necessary for?

My usecase was that I manly develop on Windows and needed some personal changes to the bot to run it on my linux computer. I guess this is really niche and I just kinda intended this issue to be more of a fyi.

I ended up solving it with docker and [this](https://github.com/electron-userland/electron-build-service/issues/9#issuecomment-704069238) solution and you could probably use WSL (haven't tried it tho)

I'm unsure if this issue is solvable without changing how the application gets build

**Comment by neopostmodern** [comment]
Given that this has limited impact and we've already documented two workarounds and I don't see any simple solution I'd close this.

Also, of your changes could benefit others I'd be happy to merge them in a PR.

**Comment by drblaui** [comment]
I am unsure if my changes are useful for "normal" users, as i just implemented that the bot sends me an email if it's stuck on a captcha so that i know i have to vnc into my computer if I'm not home and solve it for him. So it's also a very specific case

(Plus i had to rewrite how Mails are send, because I didn't want to create a sendgrid account). But I'll consider looking at other issues in the near future
