### ISSUE TITLE
PDF generation of flat pages rarely works

### ISSUE THREAD

**Issue by neopostmodern** [neopostmodern/wohnungsbot#11]

**Comment by code-schreiber** [comment]
I can confirm this behavior. Out of almost 50 applications (sent and error while sending) in a time span of 20 days, only 5 PDFs where generated. I haven't yet seen a pattern on when it works or not.

Saving PDFs is a very helpful feature of this project, thanks for your investment into this.

**Comment by neopostmodern** [comment]
I tried updating to Electron v7 (https://github.com/neopostmodern/wohnungsbot/commit/ed5ec4d8fb8b9f4f705317826b2314ed450bcbbd), hoping something might have improved on their end, but nope.
If you (or anybody else) wants to / can look into this, the relevant call is here: [helpers.js:46](https://github.com/neopostmodern/wohnungsbot/blob/master/app/middleware/helpers.js#L46)
I've wrapped it in a timeout to ensure the core functionality of the bot is not impaired, but even removing the timeout does not increase the success rates.

**Comment by neopostmodern** [comment]
Seems to be this: https://github.com/electron/electron/issues/20634

**Comment by bjbk** [comment]
With v6 it worked, v7 breaks again.
No errors, but never ends.

**Comment by bjbk** [comment]
I don't know if this is the issue, but I got it to work.  The [docs](https://electronjs.org/docs/api/web-contents#contentsprinttopdfoptions) say that `contents.printToPdf(options) returns a promise, but the example shows a callback.

This is what I got that works:

```js
ipcMain.on('printPDF', (event, arg) => {
  const pdfPath = `${app.getPath('desktop')}/${arg.name}.pdf`
  mainWindow.webContents.printToPDF({
    pageSize: 'Letter'
  }).then(data => {
    fs.writeFileSync(pdfPath, data, (err) => {
      if (err) throw err
      console.log('PDF success!')
    })
  }
  )
})
```
