### ISSUE TITLE
Bot Gets stuck.  Unable to apply to advertisements.

### ISSUE THREAD

**Issue by Sl0wB0t** [neopostmodern/wohnungsbot#110]
Bot gets stuck when attempting to make contact with Provider.  Unable to apply and send personal message.

![image](https://user-images.githubusercontent.com/108837302/177643194-95621d99-1565-40f7-a49a-0fb9db48122d.png)

**Comment by neopostmodern** [comment]
Does this only happen when applying to advertisements (as per the title)?
Where does it get stuck?
