### ISSUE TITLE
login with google account

### ISSUE THREAD

**Issue by Nikx187** [neopostmodern/wohnungsbot#117]
Hello,

unfortunately there is noy way to login with a gmail account. will there be an option in the future? Maybe a manual login option after the bot started would solve the problem.

**Comment by neopostmodern** [comment]
At the moment it's not planned, but since the same request came for Facebook (#99) maybe someone wants to tackle it for all sign-in providers?
I really appreciate your "manual login" idea, that sounds like a very reasonable approach!

**Comment by parodiniccolo** [comment]
Yeah I really need it too!

**Comment by julianhartmer** [comment]
As a workaround, you can look up your email when logged in on immoscout. Once you have it, log out and reset your password in the login prompt. Now you can also login into the bot with email and password.
