### ISSUE TITLE
Ability for bot to  paste message instead of manually typing

### ISSUE THREAD

**Issue by rajiv614** [neopostmodern/wohnungsbot#118]
Would really like to see the bot be able to paste the message rather than manually typing it. Noticed this takes quite some time as compared to how i would do it myself( paste instead of type each time)

**Comment by neopostmodern** [comment]
I think @drblaui said everything relevant. 🎨

Beside, I'm not sure why more speed would be needed in the first place and I wonder whether this would negatively impact long-term performance on another level, e.g. captcha score.
