### ISSUE TITLE
Frequent captcha

### ISSUE THREAD

**Issue by tjasagithub** [neopostmodern/wohnungsbot#119]
Hi guys! Immoscout works great, but almost every hour there is a captcha/verification needed, which means I can´t leave the bot runing 24/7. Is there any way to solve it so that catpcha woldn´t appear so often? I use wohnungsbot in windows platform. How is it with captcha on linux or mac?

Thank you :)

**Comment by neopostmodern** [comment]
AFAIK there is no difference between different operating system to how often the captchas appear. As for the feature request of an automated captcha-solver please track #87

**Comment by tjasagithub** [comment]
Okay! Thank you :))
