### ISSUE TITLE
Can't authenticate account

### ISSUE THREAD

**Issue by neopostmodern** [neopostmodern/wohnungsbot#120]
If an email challenge is posed there is no way to enter the authentication code

**Comment by neopostmodern** [comment]
If a "manual login" option (see #117) were implemented that could cover this edge-case too (if it is an edge-case), at least for now.

**Comment by timethy96** [comment]
There would also be the possibility to solve this by implementing the 2FA-login option, as the website does not use the mail-address authentication when 2FA is activated.

**Comment by herrkami** [comment]
Same issue... I can't use the bot with my plus-account. I would be willing to donate for a quick solution :)
