### ISSUE TITLE
Fails to fill e-mail field

### ISSUE THREAD

**Issue by neopostmodern** [neopostmodern/wohnungsbot#123]
*Reported via mail*

Not yet reproduced.

**Comment by neopostmodern** [comment]
Another independent report via e-mail.

Error messages in side bar:
```
Repeatedly failed to write text to "#contactForm-phoneNumber"
```
```
Repeatedly failed to write text to "#contactForm-phoneNumber"
```

Along with description (machine translated):
> The bot has just opened the text window to write to an apartment. But there was only the previous text and he did not write a new one. After a few minutes it displayed an error message "Timed out" and switched back to the search window.

The selectors (`#contactForm-phoneNumber` etc) have in principle not changed in the form.

**Comment by aecro** [comment]
I've run into the same issue with #contactForm-Message. I just barely saw what happened, it seemed like the bot was scrolling down the search results and failing to open the apartment details page, so it looked like it wasn't even close to writing a message.

**Comment by neopostmodern** [comment]
Now that 1.7 is being released I'm closing a bunch of issues that could not be linked to specific causes. Please try with the latest version and if the error still happens, re-open this issue with more details.
