### ISSUE TITLE
Links open in same WebView, rather than in browser on Windows 10

### ISSUE THREAD

**Issue by neopostmodern** [neopostmodern/wohnungsbot#13]
Tested with a link in the announcement section of the sidebar

**Comment by drblaui** [comment]
Pretty sure this only happens with one single link. The link that leads to the url where people can sponsor you/this project. The point of "failure" here is [the announcement page](https://wohnungsbot.de/announcement.html), where this exact link is the only one not containing the `target="_blank"` attribute. Changing that (which I already tried out using code) fixes this specific issue
