### ISSUE TITLE
Update GitHub action versions

### ISSUE THREAD

**Issue by neopostmodern** [neopostmodern/wohnungsbot#132]
actions affected:
- actions/checkout@v2
- actions/setup-node@v2
- actions/upload-artifact@v2
- samuelmeuli/action-electron-builder@v1

The first three are [definitely easy](https://github.com/neopostmodern/structure/commit/c984a78c7ebe109d3101c8d103c24835bab48360), the latter I haven't checked yet

**Comment by djaghofmann** [comment]
Could this be related to me having to run `npx electron .` instead of `npm run-script dev` to get it to work?

Windows x64 Wohnungsbot 1.6.0

**Comment by neopostmodern** [comment]
@djaghofmann I don't think so, but did you ever figure out your issue? @geohiehoe was facing it too.
