### ISSUE TITLE
Timeout Problem

### ISSUE THREAD

**Issue by SossenSystems** [neopostmodern/wohnungsbot#135]
Hey Clemens,

danke erstmal für das coole Kunstprojekt welches echt Hilft!

Ich habe folgenden Bug zu melden:
Wenn der Bot mal im Hintergrund war und dennoch versucht hat was zu machen kommt es zu den ganzen Timeouts in der Liste links in Rot mit der Meldung "Timed out". Das Problem ist dann, das diese Wohnungen nicht mehr angeschrieben werden können, obwohl diese noch existieren.

**Comment by Audiopicasso** [comment]
Hab leider das gleiche Problem. Etwa 50% der Anfragen können nicht abgeschickt werden, wegen Timeout Error. Programm läuft dauerhaft im Vordergrund, aber hängt sich leider auf --> timeout. Hoffe das wird bald gefixt

**Comment by neopostmodern** [comment]
Auf welchem Betriebssystem seit ihr? Tritt das Problem auch auf, wenn der Bot im Vordergrund ist?

**Comment by neopostmodern** [comment]
Now that 1.7 is being released I'm closing a bunch of issues that could not be linked to specific causes. Please try with the latest version and if the error still happens, re-open this issue with more details.
