### ISSUE TITLE
Bot gets stuck at various places

### ISSUE THREAD

**Issue by livinlarge** [neopostmodern/wohnungsbot#137]
Installed the bot yesterday (MacOS 12.4).

Bot always successfully logs in and searches for apartment but then:
Bot got stuck at the number of apartments found.
Bot got stuck at "Kontaktanfrage".
Bot got stuck at number of apartmentds found again.

2 Anfragen timed out yesterday (visible in the list to the left).
Doesn't matter if I have the window right in fron and active with the mouse or just hidden behind other windows.

No idea what I should do as there is no crashlog or anything.

Can you help me here?

**Comment by neopostmodern** [comment]
Sorry for the late reply, this somehow got lost in my inbox. 
Yeah, crashlogs would be amazing to debug this kind of issues.

My best guess would be for you to either 
- take a bunch of screenshots
- copy the console output, if you know how to launch the program from the command line
- clone the repo and try to debug it yourself

Without more specific information why/how it gets stuck I can't really look into it, there are simply too many moving parts.

**Comment by neopostmodern** [comment]
Now that 1.7 is being released I'm closing a bunch of issues that could not be linked to specific causes. Please try with the latest version and if the error still happens, re-open this issue with more details.
