### ISSUE TITLE
Signing in to Immoscout does not work

### ISSUE THREAD

**Issue by Lamalord** [neopostmodern/wohnungsbot#141]
The bot is stuck at "Anmelden" and nothing really happens.
If you could manually sign in would be great

**Comment by neopostmodern** [comment]
How does this relate to #117, #120 and PR #140 ?

**Comment by besendorf** [comment]
It looks this on my machine
![image](https://github.com/neopostmodern/wohnungsbot/assets/26350155/2ed608d6-00dc-4f17-b50d-40d7431bd932)
I guess a manual sign in would solve this

**Comment by SgtZeppelin** [comment]
I have the same problem on version 1.6.0, along with the following error:

`Stack that led to the execution of this snippet (Electron):
 at scrollIntoView (/tmp/.mount_WohnuncQopu1/resources/app.asar/app/webpack:/wohnungsbot/app/actions/botHelpers.js:154:25)
 at /tmp/.mount_WohnuncQopu1/resources/app.asar/app/webpack:/wohnungsbot/app/actions/botHelpers.js:184:11
 at next (/tmp/.mount_WohnuncQopu1/resources/app.asar/node_modules/redux-thunk/lib/index.js:23:18)
 at /tmp/.mount_WohnuncQopu1/resources/app.asar/app/webpack:/wohnungsbot/app/middleware/scheduler.js:45:10
 at dispatch (/tmp/.mount_WohnuncQopu1/resources/app.asar/node_modules/redux/lib/redux.js:667:28)
 at /tmp/.mount_WohnuncQopu1/resources/app.asar/app/webpack:/wohnungsbot/app/actions/bot.js:63:11
 at /tmp/.mount_WohnuncQopu1/resources/app.asar/app/webpack:/wohnungsbot/app/middleware/scheduler.js:42:5

Error executing JavaScript-snippet within webContents:
[TypeError] Cannot read properties of null (reading 'value')
TypeError: Cannot read properties of null (reading 'value')
    at <anonymous>:3:54
    at new Promise (<anonymous>)
    at <anonymous>:1:1

This is the code that caused the error:
new Promise((resolve, reject) => {
       try {
          resolve(document.querySelector('#username').value)
       } catch(err) {
          throw { name: err.name, message: err.message, stack: err.stack }
       }
    })
// END OF CODE
`
