### ISSUE TITLE
Can't log in to Immoscout on MacOSX

### ISSUE THREAD

**Issue by xenon5413129** [neopostmodern/wohnungsbot#146]
The bot isn't logging into Immoscout on MacOSx.

Restarting the bot causes it to skip the log-in process and jump straight to searching as an unauthenticed user.

Uninstalling the app and deleting any application files, then re-installing doesn't seem to solve the issue either.

macOS Monterey 12.4

**Comment by neopostmodern** [comment]
Closing as duplicate of #141
