### ISSUE TITLE
Stuck on login

### ISSUE THREAD

**Issue by lukeanthonymcewan** [neopostmodern/wohnungsbot#158]
Mac OS 13.4.1 (22F82)

Looks like the login feature doesn't work for immobilienscout24. The bot loads the homepage and is saying 'Anmelden' but nothing happens.

<img width="1037" alt="Screenshot 2023-08-04 at 11 20 46 am" src="https://github.com/neopostmodern/wohnungsbot/assets/66076553/98966f47-94ab-4cc1-ba98-724f4fe5b75b">

**Comment by neopostmodern** [comment]
Closing as duplicate of #141
