### ISSUE TITLE
Account e-mail field always required

### ISSUE THREAD

**Issue by neopostmodern** [neopostmodern/wohnungsbot#167]
Need to update the logic in `app/components/configurationStages/personalData.js:289`

**Comment by geohiehoe** [comment]
I could now look into the code and then would implement the opposite :D 

From this issue description it's not clear if the title "always required" is the bug or the desired outcome

**Comment by neopostmodern** [comment]
Current: it's always required
Expected: required iff the user selected the login option 'Ja',
