### ISSUE TITLE
Fails to write #contactForm-Message

### ISSUE THREAD

**Issue by hoelger** [neopostmodern/wohnungsbot#183]
Reported by mail: Application errors out with `Repeatedly failed to write text to "#contactForm-Message": <message>`

For me it works. Also this selector was not changed during 1.7 release. I double checked with immoscout online that it has the same naming. So I'm running out of options what to do.

**Comment by mdanderson120** [comment]
Hello, I have received the same error message -
Repeatedly failed to write text to "#contactForm-Message".

**Comment by neopostmodern** [comment]
Can anybody who is facing this issue confirm whether it is caused by the bot not deleting the previous text? (as in #190)

Also, what operating systems does this affect?

**Comment by neopostmodern** [comment]
This issue is very old and has not been reproduced. If it still persists with 1.8 feel free to re-open.
