### ISSUE TITLE
ARM64 release is damaged in M3

### ISSUE THREAD

**Issue by topikettunen** [neopostmodern/wohnungsbot#202]
Wohnungsbot seems to fail and gives the "Wohnungsbot is damaged and can’t be opened. You should move it to the Trash" error when trying to open it with my Macbook running the new M3 chip. Tested downloading the release from the website and also from the GitHub releases. Same error in all of them.

macOS version: Sonoma 14.3.1

**Comment by neopostmodern** [comment]
Are you sure this isn't just the bizarre macOS wording for independently distributed software? Did you do all the magic tricks?

**Comment by topikettunen** [comment]
I did try those magic tricks, but IIRC, those magic tricks tend to work only if macOS gives the error of unidentified developer, not the "Wohnungsbot is damaged and can’t be opened." Or at least they have worked like that before, but I might be wrong.

**Comment by snakekick** [comment]
Hello, i have the same error on mac 14.4.1 with  M2 Arm

**Comment by neopostmodern** [comment]
Have you tried this
```
xattr -r -d com.apple.quarantine /path/to/xyz.app
```
or
```
xattr -cr xyz.app
```
?

Can you try building from source?

Otherwise I'll try once I run into an ARM-based Mac.

**Comment by snakekick** [comment]
cool, xattr -r -d com.apple.quarantine /path/to/xyz.app that work for me . thank you

**Comment by neopostmodern** [comment]
Okay, please re-open if the issue persists after running the above magic trick.

**Comment by neopostmodern** [comment]
I've extended the website's FAQ on macOS installation.

**Comment by kalle-falck** [comment]
Just additional data point `xattr -c /Applications/Wohnungsbot.app` (adjust path as needed) did the trick for me. Running M1 & Mac OS 15.5 (24F74)
