### ISSUE TITLE
Account usage info config mismatch

### ISSUE THREAD

**Issue by neopostmodern** [neopostmodern/wohnungsbot#204]
The configuration and config confirmation page mismatch, not sure about actual bot behavior. See https://github.com/neopostmodern/wohnungsbot/issues/203#issuecomment-2071498829

**Comment by CRank1907** [comment]
Thanks for opening the bug.

At least it says "Bereits eingeloggt" when the bot starts and according to the screen it is still logged in (profile picture still visible in upper right corner).
