### ISSUE TITLE
Message won't type out, application process times out

### ISSUE THREAD

**Issue by sno** [neopostmodern/wohnungsbot#206]
1.7.1 on Windows. Application process times out in every single case. While observing the bot, it looks like it's getting stuck when trying to begin its message. The contact pop-up shows properly, but the message is never being typed out.

Exposé PDFs are created without issue for each suitable apartment.

![Screenshot 2024-06-27 134923](https://github.com/neopostmodern/wohnungsbot/assets/286645/3b1eec35-f8cc-4d93-8d14-31d57c51c813)

**Comment by mareikel** [comment]
I can replicate this on with 1.7.1 a Macbook with M3 Chip and Sonoma 14.5. The bot gets stuck while intending write the message. One of the "Letzte Bewerbungen" is blue in contrast to all the other red ones, but in the ImmoScout account I cannot see any matching Bewerbung, so not sure what the blue means.

<img width="1197" alt="Bildschirmfoto 2024-07-07 um 18 19 09" src="https://github.com/neopostmodern/wohnungsbot/assets/26602110/23f8b99e-4b7e-478c-80a3-b4ad7d84baf5">

**Comment by neopostmodern** [comment]
Might be related to #183 and (possibly) #205

**Comment by jannik-l** [comment]
Facing the same issue. Any hint on how to debug this?

**Comment by janhh011** [comment]
+1

**Comment by neopostmodern** [comment]
Can you please check if this is still an issue in with 1.8?

**Comment by sno** [comment]
Working fine for me now on macOS ARM64! With the Windows version, I had to deactivate the experimental sorting to proceed. Now I'm experiencing a weird new issue where the message text gets scrambled like it's being inserted multiple times simultaneously:

![image](https://github.com/user-attachments/assets/cfb88e68-d0d0-42f8-bceb-23c4e917ebef)

**Comment by neopostmodern** [comment]
Glad to hear one thing is fixed - but annoying to see this other bug coming back.
@sno Can you please report in #190 whether what your observing is due to (a) the text not getting deleted before being typed again or (b) acutally being typed multiple times simultaneously?
Closing here for now.
