### ISSUE TITLE
Stuck at Sortierung Ändern and can't do anything

### ISSUE THREAD

**Issue by Agni14** [neopostmodern/wohnungsbot#212]
Hello, first of all thanks a lot for this helpful tool, I was installing it to Mac, it looks like it's running but I can't select anything from the page and the bot keeps saying "Sortierung Ändern". It looks like it's not working in the end.
I have Monterey version 12.7.4 (21H1123). Can you help me please?

Vielen Dank, Liebe Grüße

Ani

**Comment by Agni14** [comment]
Sorry ti hear that you have the same problem, I hope someone can help us.

**Comment by Athaanatos** [comment]
I have the same problem here as well.

reinstalling the app did not solve it.
changing the filters did not solve it either.

Please help :D 

Thank you!

Installed on Windows 10 Pro

**Comment by neopostmodern** [comment]
Um, this might sound a bit stupid but, have you checked that the option to sort by newest flats first is disabled?

**Comment by Athaanatos** [comment]
Stupid I was **indeed** and it now works :D
Thank you sir!

**Comment by neopostmodern** [comment]
Okay, closing this issue. Since this affects multiple people, can someone tell me if they did *not* manually enable it? Or did you all enable it and then forgot about it? It's not in the default settings as far as I can see.
Further discussion of the actual issues in #114 please.

**Comment by Agni14** [comment]
I enabled it manually before using the bot.

Il sab 7 dic 2024, 15:31 neopostmodern ***@***.***> ha
scritto:

**Comment by Agni14** [comment]
I will try later, thank you for the suggestion, I hope it works for me as
well!

Il sab 7 dic 2024, 16:32 Agnese ***@***.***> ha scritto:

**Comment by Agni14** [comment]
Hey, I checked my wohnungs bot and my sortierung is at
"standardsortierung" not "sort by the newest flats first", so I still have
the issue.

Thank you

Il giorno gio 5 dic 2024 alle ore 10:28 Athaanatos ***@***.***>
ha scritto:

**Comment by neopostmodern** [comment]
That doesn't sound quite right. Have you checked the above screenshot? https://github.com/neopostmodern/wohnungsbot/issues/212#issuecomment-2525180309
