### ISSUE TITLE
Bot get's stuck at "Anzeige schreiben"

### ISSUE THREAD

**Issue by neopostmodern** [neopostmodern/wohnungsbot#24]
only sometimes

**Comment by neopostmodern** [comment]
often caused by hitting "reset" previously since the cached verdict doesn't get cleared

**Comment by neopostmodern** [comment]
it seems to be (sometimes) caused by the bot starting two application processes at the same time, for an unknown reason

**Comment by rusagent** [comment]
How to solve this temporarily? Just happened to me right now...

**Comment by neopostmodern** [comment]
Closing due to activity.
