### ISSUE TITLE
Allow to filter (exclude) flat-swaps

### ISSUE THREAD

**Issue by neopostmodern** [neopostmodern/wohnungsbot#30]

**Comment by valoricDe** [comment]
I would like to work on that. Where is the current WBS filter living? While I'm on it should I also create the other filters for https://github.com/neopostmodern/wohnungsbot/issues/29 ?

**Comment by neopostmodern** [comment]
Great!
It's two-part. First, you'd need to add a configuration option (look [here](https://github.com/neopostmodern/wohnungsbot/blob/master/app/reducers/configuration.js) and GUI for it (look [here](https://github.com/neopostmodern/wohnungsbot/blob/master/app/components/configurationStages/flatDescription.js). Second, add a filter (look [here](https://github.com/neopostmodern/wohnungsbot/blob/master/app/flat/assessment.js#L118).
I probably forgot some bits, but that should give you some starting pointers.

And yes, please tackle #29 while you're on it. Maybe #19 too.

**Comment by neopostmodern** [comment]
Closed in #42
