### ISSUE TITLE
IS24 detecting and blocking Wohnungsbot

### ISSUE THREAD

**Issue by vbwDaZLTx2EXud** [neopostmodern/wohnungsbot#33]
![Screen Shot 2020-08-04 at 12 32 47](https://user-images.githubusercontent.com/69196571/89284147-a0b17900-d64e-11ea-8cd3-463614363ee0.png)

Has anybody found a solution for this?

**Comment by neopostmodern** [comment]
Thanks for reporting this! This seems to be a new "feature" on their end, wasn't observed before as far as I'm concerned.

Will try to look into this, PRs welcome. (At a minimum the overlay should be disabled once this message appears so that users can solve the captcha manually.)

**Comment by vbwDaZLTx2EXud** [comment]
Thanks for your quick response, and for developing this in the first place. You really are a hero.

The overlay seems to still be intact, so I can't figure out a way to manually click the Captcha.. Is there something I could do to manually disable the overlay?

**Comment by neopostmodern** [comment]
No, unfortunately a patch will be necessary for this. I intentionally overlayed the window to avoid accidental clicks et cetera.

**Comment by vbwDaZLTx2EXud** [comment]
gotcha. well i will stay tuned for a patch. i'm not such a tech/coding guy but if there were anything I could do to help/support you in this please let me know!

**Comment by neopostmodern** [comment]
@vbwDaZLTx2EXud Fix released: [Wohnungsbot 1.3](https://github.com/neopostmodern/wohnungsbot/releases/tag/v1.3.0)

**Comment by Wyrrrd** [comment]
IS24 replaced reCAPTCHA with the Geetest slider. `InteractiveMode` still works, though there is a solver available [here](https://github.com/ScraperBox-Github/geetest-captcha-solver). Just leaving this here :)
