### ISSUE TITLE
Ich bin kein Roboter

### ISSUE THREAD

**Issue by shirinbarthel** [neopostmodern/wohnungsbot#35]
hi,
1mal danke, super ding und sehr hilfreich..

ich bin stuck mit dem Bot da ich angeben soll dass ich kein Roboter bin... Immoscout lässt den Bot sozusagen nicht weiterarbeiten ohne die Box zu klicken und der Bot lässt mich natürlich nicht. hab restart gemacht und bin wieder dort gelandet... kann man was tun?
danke
LG
Shirin
![Screen Shot 2020-08-08 at 13 55 19](https://user-images.githubusercontent.com/69388931/89710058-25b6ce00-d980-11ea-8c73-49498348951f.png)

**Comment by neopostmodern** [comment]
Das Problem (siehe #33) wurde in der Version 1.3 angegangen — der Bot lässt jetzt kurz die Menschen ran, wenn diese Seite kommt. 

Es gibt gerade keine automatischen Updates für macOS, also musst du es dir [hier](https://github.com/neopostmodern/wohnungsbot/releases/tag/v1.3.0) herunterladen und die Hinweise zum Öffnen befolgen!
