### ISSUE TITLE
Can't pass new cookie consent pop-up

### ISSUE THREAD

**Issue by shirinbarthel** [neopostmodern/wohnungsbot#38]
hallo,
komme leider nicht weiter mit dem wohnungsbot da ich die Cookies akzeptieren muss, aber nicht anklicken kann.. kann man da was machen?
LIEBRE GRÜ?E
shirin
![Screen Shot 2020-08-18 at 17 17 06](https://user-images.githubusercontent.com/69388931/90531868-dbe79800-e176-11ea-9c5b-2b91c5eec8dd.png)

**Comment by neopostmodern** [comment]
Ist lösbar auf jeden Fall — bin aber erst nächste Woche wieder am Rechner.
