### ISSUE TITLE
Build for macOS corrupted on GitHub Actions

### ISSUE THREAD

**Issue by neopostmodern** [neopostmodern/wohnungsbot#50]

**Comment by neopostmodern** [comment]
https://github.com/electron-userland/electron-builder/issues/4135

**Comment by neopostmodern** [comment]
Could you confirm if 1.3.3 works for you @sarsasasa?
https://github.com/neopostmodern/wohnungsbot/releases/tag/v1.3.3

**Comment by sarsasasa** [comment]
> Could you confirm if 1.3.3 works for you @sarsasasa?
> https://github.com/neopostmodern/wohnungsbot/releases/tag/v1.3.3

Unfortunately not, can't unpack the file. I tried it with various programs, incl. manually unpacking over the Terminal and other programs, seems like the file doesn't work
![Bildschirmfoto 2021-02-04 um 11 30 18](https://user-images.githubusercontent.com/77982592/106880318-824f3780-66dc-11eb-8f0d-c7c80ccb8ac8.png)
![Bildschirmfoto 2021-02-04 um 11 25 27](https://user-images.githubusercontent.com/77982592/106880321-83806480-66dc-11eb-8fb6-d6a1c1fae6a8.png)
