### ISSUE TITLE
Expand Wohnungsbot to other City's

### ISSUE THREAD

**Issue by Leo-Ltzn** [neopostmodern/wohnungsbot#64]
Hi, I'm Leo!

I hope this is the right spot to do it (I'm new on Github), but anyway, here we go:

**Do you think it would be possible to expand the project to other City's? I'm sure you could do it yourself with the code provided but given my only coding experience is Arduino based projects I don't think there is a way for me - certainly I'm not alone!**

I'm studying medicine in Heidelberg and currently looking for an affordable Flat when I stumbled upon this Project via a Forum on Facebook.

It would be great, if you could look into it and decide weather it makes sense to expand.

Kind regards, 
Leo

**Comment by neopostmodern** [comment]
While it's technically of course possible, it's a deliberate choice to limit the Wohnungsbot to Berlin. You can read a brief argument for it in the [FAQ](https://wohnungsbot.de/faq.html) or listen to the [36C3 talk](https://media.ccc.de/v/36c3-10988-wohnungsbot_an_automation-drama_in_three_acts) where this is adressed in the Q&A.

I'll close this here – but as it's open source, so...
