### ISSUE TITLE
How can I use my Immobilienscout24 Account?

### ISSUE THREAD

**Issue by sinzed** [neopostmodern/wohnungsbot#68]
I faced a strange behavior, the first time I used the bot, I don't remember how I could give it access to my account so that it was able to send the message on behalf of me, and it did.
right now don't know how to do it, and make it login to my account.
do you have any Idea?

**Comment by neopostmodern** [comment]
The ability to log into an account hasn't been implemented yet (and has not been available in the past), unfortunately.
The feature is planned though, I'd happily accept a comprehensive PR.

**Comment by neopostmodern** [comment]
Closed in 1.4.0 #75
