### ISSUE TITLE
Bot gets stuck at "Anmelden"

### ISSUE THREAD

**Issue by Wyrrrd** [neopostmodern/wohnungsbot#78]
Latest version (1.4.0), added my Immoscout24 credentials for the new login feature, now the bot is stuck on first screen saying "Anmelden".

It works again after removing the credentials.

**Comment by Wyrrrd** [comment]
Additionally, after removing the account, when the bot is supposed to say nothing, it says "Anmelden" instead.

**Comment by neopostmodern** [comment]
I couldn't reproduce the first described issue locally.
Could you try the following please: add your credentials, close the program without searching for flats, open the program, start the search. (Or have you done that already?)

I'm also not sure what you mean with the "first screen", could you describe it or upload a screenshot please?

Concerning the second issue, it feels like it's just a consequence of the first? Especially if it's gone after a restart...
