### ISSUE TITLE
Bot stuck at login (Anmelden)

### ISSUE THREAD

**Issue by flxai** [neopostmodern/wohnungsbot#80]
The bot is working great, but when I try to use the login feature ("Möchtest du dich mit deinem ImmobilienScout24-Account anmelden?") and enter my credentials the bot gets stuck saying "Anmelden" at startup.
The bot's window always had focus and retrying multiple times didn't solve it unfortunately.
A way to circumvent the problem is to reset the bot ("Bot zurücksetzen"), but then it skips login altogether.

Is this a known problem? Can this be fixed by the user?

Thanks

**EDIT**: When I call the bot from a terminal, it logs the following errors:

```
[...]
isElementInViewport([data-id="131190768"]) called on non-existent element
isElementInViewport([data-id="131215812"]) called on non-existent element
[...]
```

Has ImmobilienScout24 changed their layout? I am using version 1.4.0. Is this already fixed in a later version?

**Comment by flxai** [comment]
Yes, the credentials should be fine. I triple checked them within the bot as well as the website. I can see the bot opening the popup menu on the top right of the website but then the log aggregates the errors mentioned above. Here's a (blurred) screenshot:

![image](https://user-images.githubusercontent.com/10831300/149986893-121b6b8c-575b-4ba8-a7a2-0375b7b1d682.png)

**Comment by neopostmodern** [comment]
Strange. I just tested it on my end and it worked just fine, multiple times.

The log output is quite likely unrelated from what I can tell. 

Just to be sure I understand it correctly: the popup menu is opened and then the bot clicks somewhere outside of it and it closes again?

**Comment by flxai** [comment]
Sorry yes, the log is unrelated. I checked multiple times again and this is the behaviour:

1. The bot is started by clicking *Starten*.
2. The bot says *Anmelden*.
3. It takes 300 seconds for a timeout. This is then logged as follows:
  ```
  Error during login: Error: Timed out
  ABORT - called with reason ABORTION_ERROR - some activities will be suspended for 10000
  ABORT - end of process, return to normal
  ```

At step 3, the popup menu is showing at the same time the error messages appear. No login attempt is visible. I have again checked the credentials but they should work. Maybe this is an issue with [i3](https://i3wm.org/)? I tried focusing the window in all the variants I know (floating window, fullscreen, tiled, etc).

**Comment by flxai** [comment]
I could reproduce it by transfering `$XDG_CONFIG/Wohnungsbot`, or `~/.config/Wohnungsbot` to another device. Seems like some caching error. If you're interested I can send you the relevant files.

I solved it by removing the directory mentioned above after creating a backup of the `config.json` file inside. Thanks for your time.
