### ISSUE TITLE
Bot stuck at aquiring details of exposé (Wohnung ... suchen)

### ISSUE THREAD

**Issue by flxai** [neopostmodern/wohnungsbot#82]
The bot is stuck at aquiring details of exposé:

![image](https://user-images.githubusercontent.com/10831300/150639176-9e088aff-85c1-4638-9115-5f13520d2d8f.png)

The website the bot is loading stays white forever. Even waiting hours did not help. Clicking reset (Bot zurücksetzen) doesn't do the trick and the bot is stuck in the same situation. This is reproducible for me after a clean start on a Linux system using XFCE.

Had this ever happened to somebody else? Is this maybe connected to #81?

I had problems earlier (#80) that could be fixed by removing a cache directory (`~/.config/Wohnungsbot`) that I found by running `strace`. Are there any other directories I might be missing and could try to remove? Or some other kind of cache?

**Comment by neopostmodern** [comment]
This should be covered by a timeout. I'd have to check at what point in the application process the timeout starts. Maybe it needs to be included in the timeout bracket or get a timeout on its own.
Alternatively a solution to #81 could potentially fix this, if there was some generic safe-guard in place.

**Comment by neopostmodern** [comment]
Now that 1.7 is being released I'm closing a bunch of issues that could not be linked to specific causes. Please try with the latest version and if the error still happens, re-open this issue with more details.
