### ISSUE TITLE
Keine Tauschwohnungen - But they still appear

### ISSUE THREAD

**Issue by glonjk** [neopostmodern/wohnungsbot#85]
Is this maybe the reasonw why the Bot is not displaying appartments that actually should appear. I applied now manually but it was too late :(

**Comment by glonjk** [comment]
![Uploading jo.jpg…]()

**Comment by glonjk** [comment]
![jo](https://user-images.githubusercontent.com/98375743/151164630-76c4815c-9152-4ed7-ab3e-ee3ae1dd2b55.jpg)

**Comment by neopostmodern** [comment]
The bot does not alter the IS24 website itself, so Tauschwohnungen appearing in the list is per se not a problem. Unfortunately your overlays are not drawing correclty (see #81) so it's hard to tell if the bot filtered out the flat correctly, but unless it actually starts applying to the flat I'd assume the filter is working as intended. If it's not applying to flats it should apply to that could be a different issue, but the flats don't need to be visible on screen to be registered.
