### ISSUE TITLE
Repeatedly failed to write text to "#contactForm-Message"

### ISSUE THREAD

**Issue by Malemo** [neopostmodern/wohnungsbot#88]
Somehow sometimes the bot fails to apply on a flat and sends out this error note. Really frutrating :(

**Comment by neopostmodern** [comment]
Could you please post a screenshot or ideally (video) screencapture of the problem? That could help to identify the issue.

**Comment by Malemo** [comment]
![Screenshot 2022-01-28 115718](https://user-images.githubusercontent.com/98513997/151535387-3bb7c1c9-a82a-4c6d-ad6e-eca34d3d21de.png)

**Comment by neopostmodern** [comment]
Thanks for the image, but I guess I wasn't precise enough: it would need to be an image/video of the situation when it fails to apply (with the form still visible). Or can you describe in words what happened before the error message appeared?

**Comment by Malemo** [comment]
The bot fills in the form but then after completing the self writting text the screen of the search comes up again. On that page he will still say "Antrag ausfüllen" while scrolling to the very end of the page. After he gets there, the error appears and he restarts the  search.

**Comment by neopostmodern** [comment]
Now that 1.7 is being released I'm closing a bunch of issues that could not be linked to specific causes. Please try with the latest version and if the error still happens, re-open this issue with more details.
