### ISSUE TITLE
Shows Fehler 404 straight after the log-in

### ISSUE THREAD

**Issue by MGodo** [neopostmodern/wohnungsbot#91]
<img width="819" alt="Screenshot 2022-02-07 at 12 07 48" src="https://user-images.githubusercontent.com/3331873/152777509-632f5733-a131-4326-8045-2c8c1e0d1534.png">

After the log in, the bot stumbles upon the Fehler 404, and no action helps to go beyond it. Reloading of the bot does not help. Any other action I could do?

Many thanks!

**Comment by neopostmodern** [comment]
To get out of this situation you could try the following:
- close the app
- open the app
- go straight to _Wer bist du?_ (without launching the search)
- disable IS24 account option
- launch the bot/search and wait for logout
- go back to _Wer bist du?_
- re-enable account

I have no idea where your 404 comes from, it doesn't reproduce for me. Could it be #79? That can be circumvented by adding a minimum flat size (e.g. 1m²).

**Comment by TheManohar** [comment]
I had this issue too and adding a minimum flat size (1m²) helped me get over this error

**Comment by MGodo** [comment]
Thank you - the last point helped! (#79)
