### ISSUE TITLE
Bot gets stuck after opening a link

### ISSUE THREAD

**Issue by fetamauro** [neopostmodern/wohnungsbot#95]
After the initial search, it gets to this point where there is an external link automatically opened on my browser. The bot says 
 "Wohnung 131845062 genauer anschauen!" but won't go back to work after that. It freezes and can't go back to the search. Mac version
screenshot here:
<img width="1288" alt="image" src="https://user-images.githubusercontent.com/100873040/156636519-c7fa754f-02ef-429e-96d7-a0c60a57152a.png">

**Comment by Sashimisu** [comment]
Hi,

I have the same issue on Windows. Please, let me know when it's resolved. 
I have already tried resetting the Bot and restarting. The bot will run the search again and gets stuck on the first matching offer.

**Comment by Marsinator** [comment]
experiencing the same issue

**Comment by Sl0wB0t** [comment]
Experiencing same issue.  Windows Bot ver : 1.5.0

**Comment by neopostmodern** [comment]
Now that 1.7 is being released I'm closing a bunch of issues that could not be linked to specific causes. Please try with the latest version and if the error still happens, re-open this issue with more details.
